name: Build and Upload Leaf
on:
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
          
      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          
      - name: build project
        run: dotnet build -c Release
  
      - name: create nuget package
        run: dotnet pack Leaf/Leaf.csproj -c Release --output nuget
  
      - name: upload nuget package artifact
        uses: actions/upload-artifact@v4
        with:
          path: nuget/*
        
      - name: publish to nuget
        run: dotnet nuget push nuget/* --api-key ${{secrets.APIKEY}} --source https://api.nuget.org/v3/index.json